import random
import time

a = "alk!3qworlanfj"
b = "dfkjlqoiroqpslfkfoq"
c = "dkfkdjjqmsjfnwkalskdjf"
d = "djqiueiotioioqqsnfkqiriotqpp"
e = "fakjiq"
f = "hellowodfjak"
g = "qw!#&$*fsaqqwerok"
h = "fjksa;pqoieeofijjhbnnmf"
i = "moqiwfk"
j = "qiirijjnjnhcmz!&#doo"
k = "diuuruo"
l = "siqbar102837775881"
m = "qioooqpriiijjdrfmnniz$"
n = "dkfjioqjiouiofjdklmn"
o = "uhjfdnj!@^-="
p = "ulhaqiruiooidufiuoqiuij"
q = "iopfj!^*^*#&^&*!i"
r = "*fjkqiiiiiqifljljlkjfn"
s = "suiiianfkpppqo"
t = "tryjnnnmdoola;kokfo"
u = "wprkrjqnrdlfmfzldnjTdjTsmsepckarnldudnjTwy"
v = "dhsmfskssjansktlssk"
w = "sksjwhgdkgo!@#!dk"
x = "whdnqlsqhrhtlvekwhsskwjdakffhalclehfhr"
y = "hldrlf;dehqhrhtlvek"
z = "dkfjdskljiqiouuifjklwkldfjjsdmm,mxmkmzmkakjkjqopropoproproqihjfkmvmnjn" 
    
aaa = "alk!3qworlanfjqwef"
baa = "dfkjlqoiroqpslqweffkfoq"
caa = "dkfkdjjqmsjqweffnwkalskdjf"
daa = "djqiueioqweftioioqqsnfkqiriotqpp"
eaa = "fakjiwqfeq"
faa = "hellowodfjakqwef"
gaa = "qw!#&$*fsaqqqwefwerok"
haa = "fjksa;pqoqwfeieeofijjhbnnmf"
iaa = "moqiwqwfefk"
jaa = "qiirijjnjnhcmz!&qwef#doo"
kaa = "diuurwqefqweqweffqwfeuo"
laa = "siqbar102837775qqqwefwefwef881"
maa = "qioooqpriiijjdrfmnqeqwqwfeefwfniz$"
naa = "dkfjioqjiouiofqwefqwefjdklmn"
oaa = "uhjfdnj!qqwfeweqf@^-="
paa = "ulhaqiruiooidufiqfewuoqiuij"
qaa = "iopfj!^*^*#&^qwefqwfe&*!i"
raa = "*fjkqiiiiiqiflqwefjljlkjfn"
saa = "suiiianfkpppqwfeqo"
taa = "tryjnnnmdoola;koqwefkfo"
uaa = "wprkrjqnrdlfmfzldnqwefqfwejTdjTsmsepckarnldudnjTwy"
vaa = "dhsmfskssjansktlsqwefsk"
waa = "sksjwhgdkgo!@#!dkqwef"
xaa = "whdnqlsqhrhtlvekwhqwefsskwjdakffhalclehfhr"
yaa = "hldrlf;dehqhrhtlqwefvek"
zaa = "dkfjdskljiqiouuifjklwkldsaffjjsdmm,mxmkmzmkakjkjqopropoproproqihjfkmvmnjn"

abb = "alk!3qworlanfjrterethrhe"
bbb = "dfkjlqoiroqpslfkerthfoq"
cbb = "dkfkdjjqmsjfrthenerehtrhwkalskdjf"
dbb = "djqiueioterhtthreioioqqsnfkqiriotqpp"
ebb = "fakerthrthejiq"
fbb = "hellowodfjerthrerththeak"
gbb = "qw!#&$*fsaqerhqwerok"
hbb = "fjksa;ptytyqoieeofijjhbnnmf"
ibb = "moqiwfytyk"
jbb = "qiirijjnjntytmyhcmz!&#doo"
kbb = "diuurnrthrrtnhtnhruo"
lbb = "siqbar10283777rtnhrtnhrtnh5881"
mbb = "qioooqpriiijjdrrhntrtnhnhrfmnniz$"
nbb = "dkfjioqjiouiorthnrthntrnhthrfjdklmn"
obb = "uhjfdnj!rtrrtnhtnhnh@^-="
pbb = "ulhaqiruiooidufrtnhrtnhrtnhiuoqiuij"
qbb = "iopfj!^*^*#&^&rtnh*!i"
rbb = "*fjkqiiiiiqifrthnljljlkjfn"
sbb = "suiiianfkprnhppqo"
tbb = "tryjnnnmdoola;korthnkfo"
ubb = "wprkrjqnrdlfmfzlrthndnjTdjTsmsepckarnldudnjTwy"
vbb = "dhsmfskssjansrtnhktlssk"
wbb = "sksjwhgdkgo!@#!drtnrtnhk"
xbb = "whdnqlsqhrhtlvekwhsrnhskwjdakffhalclehfhr"
ybb = "hldrlf;dehqhrhtlvrtnhek"
zbb = "dkfjdskljiqiournthuifjklwkldfjjsdmm,mxmkmzmkakjkjqopropoproproqihjfkmvmnjn"

acc = "alk!3qworyikykilakyitnfj"
bcc= "dfkjlqoiroqpslfkfotyikytyityktykiikkitq"
ccc = "dkfkdjjqmsjfnwkalstytyktytykikiikikdjf"
dcc = "djqiueiotioiotykiyytkiykititkqqsnfkqiriotqpp"
ecc = "faktykittykktyiiykijiq"
fcc = "hellowodykityitykikykifjak"
gcc = "qw!#&$*fsaqqwtykttyikyikierok"
hcc = "fjksa;pqoieeokyitftytykikiijjhbnnmf"
icc = "moqiwtyittykiykikfk"
jcc = "qiirijjnjtyikyiknhcmz!&#doo"
kcc = "diutykikityuruo"
lcc = "siqbar102837775kyiykit881"
mcc = "qioooqpriiijjdrfmnntykiikykiiz$"
ncc = "dkfjioqjiouiotyikykityktykiitfjdklmn"
occ = "uhjfdnj!tykiykittyki@^-="
pcc = "ulhaqiruiooidufiuoytkiykitykitykitqiuij"
qcc = "iopfj!^*^*tykiykittyki#&^&*!i"
rcc = "*fjkqiiiiiqifljljlkjtykitykitykifn"
scc = "suiiianfkpppytikyttyikkiqo"
tcc = "tryjnnnmdoola;kotykikfo"
ucc = "wprkrjqnrdlfmfzyikykittykityildnjTdjTsmsepckarnldudnjTwy"
vcc = "dhsmfskssjansktyiktlssk"
wcc = "sksjwhgdkgotkyi!@#!dk"
xcc = "whdnqlsqhrhtlvekitykwhsskwjdakffhalclehfhr"
ycc = "hldrlf;dehqhrhtlykitvek"
zcc = "dkfjdskljiqiouuifjkltykiwkldfjjsdmm,mxmkmzmkakjkjqopropoproproqihjfkmvmnjn"

add = "alk!3qworlanftyij"
bdd = "dfkjlqoiroqpstyiktlfkfoq"
cdd = "dkfkdjjqmsytkijfnwkalskdjf"
ddd = "djqiueiotykitioioqqsnfkqiriotqpp"
edd = "fakwwrthrthjiq"
fdd = "hellowodfwrhtwrthjak"
gdd = "qw!#&$*fsaqqwewrhtrthwrok"
hdd = "fjksa;pqoieewrhwrhofijjhbnnmf"
idd = "moqiwwrhtwrthfk"
jdd = "qiirijjnjnwrthwthhcmz!&#doo"
kdd = "diuuwrhtwrthruo"
ldd = "siqbar1028377758wrthwth81"
mdd = "qioooqpriiijjdrwrthwrthfmnniz$"
ndd = "dkfjioqjiouiowrthfjdklmn"
odd = "uhjfdnj!@^wrthwrh-="
pdd = "ulhaqiruiooidufirwthuoqiuij"
qdd = "iopfj!^*^*#&^&wrth*!i"
rdd = "*fjkqiiiiiqiflwrthjljlkjfn"
sdd = "suiiianfkpppwrthqo"
tdd = "tryjnnnmdoola;kokfryhrrhyo"
udd = "wprkrjqnrdlfmfzldnjTdjTryhsmsepckarnldudnjTwy"
vdd = "dhsmfskssjansktlssryhryhk"
wdd = "sksjwhgdkgo!@#!dkrhyryhr"
xdd = "whdnqlsqhrhtlrhyryhvekwhsskwjdakffhalclehfhr"
ydd = "hldrlf;dryhryhehqhrhtlvek"
zdd = "dkryhryhfjdskljiqiouuifjklwkldfjjsdmm,mxmkmzmkakjkjqopropoproproqihjfkmvmnjn"

aee = "alk!3qworlanfjrhryh"
bee = "dfkjlqoiroqpslfkforyhrhyq"
cee = "dkfkdjjqmsjfnryhryhwkalskdjf"
dee = "djqiueioryhryhtioioqqsnfkqiriotqpp"
eee = "fakjiqrhy"
fee = "hellowodfjakryrhy"
gee = "qw!#&$*fsaqqryhwerok"
hee = "fjksa;pqoiryheeofijjhbnnmf"
iee = "moqiwfkrryh"
jee = "qiirijjryhnjnhcmz!&#doo"
kee = "diuurryhuo"
lee = "siqbar102837775881ryh"
mee = "qioooqpriiijjdrfmryhnniz$"
nee = "dkfjioqjiouioryrryhfjdklmn"
oee = "uhjfdnj!@^-ryh="
pee = "ulhaqiruiooidufiuryhoqiuij"
qee = "iopfj!^*^*#&^&*ryh!i"
ree = "*fjkqiiiiiqifryhljljlkjfn"
see = "suiiianfkppryhpqo"
tee = "tryjnnnmdoola;kokforyh"
uee = "wprkrjqnrdlfmfzldryhnjTdjTsmsepckarnldudnjTwy"
vee = "dhsmfskssjansktryhlssk"
wee = "sksjwhgdkgo!@ryh#!dk"
xee = "whdnqlsqhrhtlvekwhryhsskwjdakffhalclehfhr"
yee = "hldrlf;dehqhrhtlryhvek"
zee = "dkfjdskljiqiouuifjrhyklwkldfjjsdmm,mxmkmzmkakjkjqopropoproproqihjfkmvmnjn"

aff = "alk!3qworlaasdfadfnfj"
bff = "dfkjlqoiroqpslfkfagsoq"
cff = "dkfkdjjqmsjfnwkalskgsfdjf"
dff = "djqiueiotioioqqsnfkqqwgiriotqpp"
eff = "fakdsafasafaadsadsfadsfjiq"
fff = "hellowodfjasdfasdqak"
gff = "qw!#&$*fsaqqwetfdsarok"
hff = "fjksa;pqoqwetqwetqieeofijjhbnnmf"
iff = "moqiwfqwetk"
jff= "qiirijjnjqwetqwetqnhcmz!&#doo"
kff = "diuuruoqwt"
lff = "siqbar10283qweqt7775881"
mff = "qioooqpriiiqwetjjdrfmnniz$"
nff = "dkfjioqjqetiouiofjdklmn"
off = "uhjfdnjerq!@^-="
pff = "ulhaqiruioasdfoidufiuoqiuij"
qff = "iopfj!^*^*#&^&*asdf!i"
rff = "*fjkqiiiiiqifadsfljljlkjfn"
sff = "suiiianfkppasdfpqo"
tff = "tryjnnnmdoolasdfa;kokfo"
uff = "wprkrjqnrdlfmfzldasdfnjTdjTsmsepckarnldudnjTwy"
vff = "dhsmfskssjansktlsadfssk"
wff = "sksjwhgdkgo!@#!adfhdk"
xff = "whdnqlsqhrhtlvekwadfghsskwjdakffhalclehfhr"
yff = "hldrlf;dehqhrhtlasvek"
zff = "dkfjdskljiqiouuasdifjklwkldfjjsdmm,mxmkmzmkakjkjqopropoproproqihjfkmvmnjn"

agg = "alk!3qworlasadfnfj"
bgg = "dfkjlqoiroqpslfkasfoq"
cgg = "dkfkdjjqmsjfnwkafkpoklskdjf"
dgg = "djqiueiotiofpikpioqqsnfkqiriotqpp"
egg = "fakjiqqojoij"
fgg = "hellowodfjakdfjioj"
ggg = "qw!#&$*fsaqqpl;werok"
hgg = "fjksa;pqooklieeofijjhbnnmf"
igg = "moqiwfkdfd"
jgg = "qiirijjnjmkmnhcmz!&#doo"
kgg = "diuuruxzczo"
lgg = "siqbar10283777588zxc1"
mgg = "qioooqpriiijjdrfmnqwrgniz$"
ngg = "dkfjioqjiouioplpqifjdklmn"
ogg = "uhjfdnj!@^ooko-="
pgg = "ulhaqiruiooidufiuoqifkjiuij"
qgg = "iopfj!^*^*#&^&*!ggqeri"
rgg = "*fjkqiiiiiqiflgadsfjljlkjfn"
sgg = "suiiianfkpppqog"
tgg = "tryjnnnmdoola;kokfgo"
ugg = "wprkrjqnrdlfmfzldnfffjTdjTsmsepckarnldudnjTwy"
vgg = "dhsmfskssjansktlffssk"
wgg = "sksjwhgdkgo!@adsf#!dk"
xgg = "whdnqlsqhrhtlvekwfdhsskwjdakffhalclehfhr"
ygg = "hldrlf;dehqhrhtasdlvek"
zgg = "dkfjdskljiqiasdfouuifjklwkldfjjsdmm,mxmkmzmkakjkjqopropoproproqihjfkmvmnjn"

ahh = "alk!3qworlaplllnfj"
bhh = "dfkjlqoiroqpslfkfgkpokpoq"
chh = "dkfkdjjqmsjfnwkagokpokpokplskdjf"
dhh = "djqiueiotiogkjijioqqsnfkqiriotqpp"
ehh = "fakjiqgijij"
fhh = "hellowodfjagiojiok"
ghh = "qw!#&$*fsaqqwerghiulok"
hhh = "fjksa;pqoiefplojulkeofijjhbnnmf"
ihh = "moqiwfplpqlk"
jhh = "qiirijjnjnhcfokokmz!&#doo"
khh = "diuuruffgoqoo"
lhh = "siqbar102837775881ggw1qef"
mhh = "qioooqpriiijjdrfmnnhjkiz$"
nhh = "dkfjioqjiouiofasdffhjdklmn"
ohh = "uhjfdnj!@^-adsf="
phh = "ulhaqiruiooidufiuoqasdfiuij"
qhh = "iopfj!^*^*#&^&*aaaff!i"
rhh = "*fjkqiiiiiqiflgglpjljlkjfn"
shh = "suiiianfkpppjkqo"
thh = "tryjnnnmdoola;ghfkokfo"
uhh = "wprkrjqnrdlfwrtmfzldnjTdjTsmsepckarnldudnjTwy"
vhh = "dhsmfskssjanskfqtlssk"
whh = "sksjwhgdkgo!@q#!dk"
xhh = "whdnqlsqhefrhtlvekwhsskwjdakffhalclehfhr"
yhh = "hldrlf;deqsdfhqhrhtlvek"
zhh = "dkfjdskljiqifiiouuifjklwkldfjjsdmm,mxmkmzmkakjkjqopropoproproqihjfkmvmnjn"

aii = "alk!3qworlplanfj"
bii = "dfkjlqoiroqpslfkfokkq"
cii = "dkfkdjjqmsjfnyuwioopkalskdjf"
dii = "djqiueioqwerttioioqqsnfkqiriotqpp"
eii = "fakjifdfsq"
fii = "hellowodfqqjadfk"
gii = "qw!#&$*fsaqqwerqqfreok"
hii = "fjksa;pqoiefqrteofijjhbnnmf"
iii = "moqiwfokfiik"
jii = "qiirijjnjdqeplnhcmz!&#doo"
kii = "diuudfghuruo"
lii = "siqbar10283hq137775881"
mii = "qioooqffgghpriiijjdrfmnniz$"
nii = "dkfdwrejioqjiouiofjdklmn"
oii = "ufffhjfdnj!@^-="
pii = "ulhasdfaqiruiooidufiuoqiuij"
qii = "iopfj!^*^*#&^&ddsfsdf*!i"
rii = "*fjkqiiiiiqifqetyljljlkjfn"
sii = "suiiianfkpppasdfqo"
tii = "tryjnnnmdoolaqrrfr;kokfo"
uii = "wprkrjqnrdlfmfzldwetqnjTdjTsmsepckarnldudnjTwy"
vii = "dhsmfskssjanwfwetrsktlssk"
wii = "sksjwhgdkgfkko!@#!dk"
xii = "whdnqlsqhrhtlvsawefwsekwhsskwjdakffhalclehfhr"
yii = "hldrlf;dehdsfdfqhrhtlvek"
zii = "dkfjdsfsdfdskljiqiouuifjklwkldfjjsdmm,mxmkmzmkakjkjqopropoproproqihjfkmvmnjn"

    

        
def password():
    print("암호화하실 문장을 입력하여주세요.")
    password_str = input("")
    password_str_len = len(password_str)
    password_str_list = list(password_str[0:password_str_len])
    print(password_str)
    print(password_str_len)
    print(password_str_list)
    
    if password_str_list[0] == "a":
        random_nu = random.randint(1, 10)
        
        if random_nu == 1:
            one_letter




print("무엇을 하시겠습니까?")
print("----------------------")
print("1. 암호화")
print("2. 복호화")
print("----------------------")
choice = int(input("숫자만 입력 : "))

if choice == 1:
    print("암호화 프로그램 시작")
    print("")
    password()

